# Generated by Django 3.0.6 on 2020-05-08 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date and time of entry creation.', verbose_name='timestamp')),
                ('url', models.URLField(help_text='URL of the resource you want to share.', max_length=400, unique=True, verbose_name='URL')),
                ('image_url', models.URLField(blank=True, help_text='The image of the resource.', max_length=400, verbose_name='image URL')),
                ('_author', models.ForeignKey(blank=True, db_column='author', help_text='The user who posted entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'entry',
                'verbose_name_plural': 'entries',
            },
        ),
    ]
