# Generated by Django 3.0.6 on 2020-05-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL of the resource you want to share.', max_length=400, unique=True, verbose_name='URL')),
                ('image_url', models.URLField(blank=True, help_text='The image of the resource.', max_length=400, verbose_name='image URL')),
            ],
            options={
                'verbose_name': 'entry',
                'verbose_name_plural': 'entries',
            },
        ),
    ]
