# Generated by Django 3.0.6 on 2020-05-25 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'URL'), (1, 'Image'), (2, 'Video'), (3, 'Youtube video')], default=0, help_text='Supported entry type.', verbose_name='type')),
                ('url', models.URLField(help_text='URL of the resource to share.', max_length=400, verbose_name='URL')),
                ('label', models.CharField(blank=True, help_text='Entry label (optional).', max_length=100, verbose_name='label')),
            ],
            options={
                'verbose_name': 'entry',
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='EntrySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(blank=True, help_text='Entry set name (optional).', max_length=50, verbose_name='name')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('entries', models.ManyToManyField(help_text='Entries that this set contains.', related_name='sets', to='entries.Entry', verbose_name='entries')),
            ],
            options={
                'verbose_name': 'entry set',
                'verbose_name_plural': 'entry sets',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='origin',
            field=models.ForeignKey(editable=False, help_text='Original entry set of the entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_entries', to='entries.EntrySet', verbose_name='origin'),
        ),
    ]
