# Generated by Django 3.0.6 on 2020-05-09 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date and time of entry creation.', verbose_name='timestamp')),
                ('text', models.CharField(help_text='Reply text.', max_length=200, verbose_name='text')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('_author', models.ForeignKey(blank=True, db_column='author', help_text='The user who posted entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('entry', models.ForeignKey(help_text='Entry to which reply is attached.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='entries.Entry', verbose_name='related entry')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text="Parent reply if it's not entry reply.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='entries.Reply', verbose_name='parent reply')),
            ],
            options={
                'verbose_name': 'reply',
                'verbose_name_plural': 'replies',
            },
        ),
    ]
