FROM python:3.8

ENV PYTHONUNBUFFERED 1

ENV PIP_NO_CACHE_DIR false

WORKDIR /app

COPY Pipfile Pipfile.lock ./

RUN pip install --upgrade pip && pip install pipenv

RUN pipenv install --deploy --system --dev

COPY . .

EXPOSE 8000

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
