# Generated by Django 3.0.6 on 2020-05-25 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('text', models.CharField(help_text='Reply text.', max_length=200, verbose_name='text')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('entryset', models.ForeignKey(help_text='Entries set to which the reply belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='entries.EntrySet', verbose_name='entry set')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text="Parent reply if it's not root reply.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='replies.Reply', verbose_name='parent reply')),
            ],
            options={
                'verbose_name': 'reply',
                'verbose_name_plural': 'replies',
            },
        ),
    ]
