# Generated by Django 3.0.7 on 2020-07-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'URL'), (1, 'Image'), (2, 'Video'), (3, 'Youtube video'), (4, 'Audio')], default=0, help_text='Supported entry type.', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='entryset',
            name='name',
            field=models.CharField(blank=True, help_text='Set name (optional).', max_length=50, verbose_name='name'),
        ),
    ]
